Update azure-pipelines.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -80,6 +80,14 @@ stages:
         environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
         commandOptions: '-auto-approve -no-color -lock=false'
 
+    - script: |
+              if [ $? -ne 0 ]; then
+                terraform state push errored.tfstate
+              fi
+            displayName: 'Push Terraform state if apply failed'
+            condition: failed()  # Run this step only if the previous step failed
+
+
 
 
 - stage: Build
